import Vue from 'vue'
import VueRouter from 'vue-router'
import ElementUI from 'element-ui'
import './assets/index.css'
import finger from './vue-finger.js'
import VueQrcode from '@xkeshi/vue-qrcode'
import ajax from 'djax'